### ISSUE TITLE
Tasks by fnuess lost while merging?

### ISSUE THREAD

**Issue by bellerophons-pegasus** [bellerophons-pegasus/ssciwr_sdc_team14#10]
I just noticed that the code introduced by @fnuess for his tasks into the jupyter-notebook are not there anymore on main.
I'm not sure how it happened.

Could you have a look?

**Comment by fnuess** [comment]
It seems that the changes were lost when #8 was merged. One can see there that my tasks are not present in the file-to-merge. I'll push another branch.
