### ISSUE TITLE
A lot of open branches

### ISSUE THREAD

**Issue by iulusoy** [bellerophons-pegasus/ssciwr_sdc_team14#25]
While it is very nice that you open branches with meaningful names, once the work in the branch is done and the branch is merged with main (or another branch), it can safely be deleted.

**Comment by bellerophons-pegasus** [comment]
Thanks. I'll go through my branches and delete them accordingly.

**Comment by bellerophons-pegasus** [comment]
@rajanish4 could you have a look at two remaining branches that you created and see if you can safely delete them?
