### ISSUE TITLE
Preparation for unit3

### ISSUE THREAD

**Issue by bellerophons-pegasus** [bellerophons-pegasus/ssciwr_sdc_team14#27]
Hi @rajanish4 and @fnuess 
I'm already in the middle of the process of preparing our repository for the next unit tomorrow. You will notice that the main branch now has an updated `.gitignore` and new `.gitattributes` and `requirements.txt`. 

For readthedocs my account is ready and the initial documentation for this repository was built: https://ssciwr-sdc-team14.readthedocs.io/en/latest/

I'm now going to include the sphinx source directory

**Comment by bellerophons-pegasus** [comment]
Updates done to main.

What now remains is to include our modules.

**Comment by rajanish4** [comment]
ok i will push my python file, @fnuess you can add your code to my numeric_method.py file
