### ISSUE TITLE
cant commit my new branch !

### ISSUE THREAD

**Issue by rajanish4** [bellerophons-pegasus/ssciwr_sdc_team14#7]
getting error python permission denied while committing, some problem with hook i guess, does anyone know solution to this?

**Comment by bellerophons-pegasus** [comment]
Could you maybe add some more information? The last command you executed and the full error message?

**Comment by rajanish4** [comment]
after modifying the jupyter notebook and trying to commit i get this:
$ git commit -m"finished my tasks"
/usr/bin/env: ‘python’: Permission denied

**Comment by bellerophons-pegasus** [comment]
try updating virtualenv
`python -m pip install --upgrade virtualenv`

**Comment by rajanish4** [comment]
ok so apparently i couldnt do that, so I cloned the main repo again and copied my code in my branch and pushed it :)
